### ISSUE TITLE
Adding fake headers

### ISSUE THREAD

**Issue by nicolas-grekas** [lyrixx/test#11]
So, decorating responses is complicated :)

AsyncResponse to the rescue.
Here is a fake client that works BUT requires removing the `final` keyword on `AsyncResponse`:

```php
final class FakeCacheHeaderClient implements HttpClientInterface
{
    use AsyncDecoratorTrait;

    public function request(string $method, string $url, array $options = []): ResponseInterface
    {
        return new class($this->client, $method, $url, $options) extends AsyncResponse {
            public function getHeaders(bool $throw = true): array
            {
                $headers = parent::getHeaders($throw);

                // FIXME: but a lower value!
                // One month
                $headers['cache-control'] = 'public, max-age=2592000, s-maxage=2592000';

                return $headers;
            }
        };
    }
}
```

The alternative (not using `AsyncResponse`) requires implementing the `stream()` method to unwrap + rewrap the passed responses so that the inner client doesn't see any custom response objects but the consumer sees only them.

**Comment by lyrixx** [comment]
removing the final seems a good idea to me, WDYT?

---

this example is really clear, I like it !

**Comment by nicolas-grekas** [comment]
yes, makes sense, PR welcome. 6.3?

**Comment by lyrixx** [comment]
okay, I'll do that 👍🏼

**Comment by lyrixx** [comment]
thanks
